group 'com.example.futronic_fingerprint_scanner'
version '1.0'


rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'com.example.futronic_fingerprint_scanner'
    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdkVersion 16
    }


}

dependencies {
    implementation 'com.android.support:support-v4:28.0.0'
   implementation project(path: ':ftrWsqAndroidHelper-release')
    implementation project(path: ':ftrScanApiAndroidHelperUsbHost-release')
}